num_classes: &num_classes 81
runtime:
    aligned: True
    async_norm: True
    special_bn_init: True
    fp16: True

mosaic: &mosaic
  type: mosaic
  kwargs:
    extra_input: True
    tar_size: 640
    fill_color: 0

random_perspective: &random_perspective
  type: random_perspective_yolox
  kwargs:
    degrees: 10.0 # 0.0
    translate: 0.1
    scale: [0.1, 2.0] # 0.5
    shear: 2.0 # 0.0
    perspective: 0.0
    fill_color: 0  # 0
    border: [-320, -320]

augment_hsv: &augment_hsv
  type: augment_hsv
  kwargs:
    hgain: 0.015
    sgain: 0.7
    vgain: 0.4
    color_mode: 'BGR'

mixup: &mixup
  type: yolox_mixup_cv2
  kwargs:
    extra_input: True
    input_size: [640, 640]
    mixup_scale: [0.8, 1.6]
    fill_color: 0

flip: &flip
  type: flip
  kwargs:
    flip_p: 0.5

to_tensor: &to_tensor
  type: custom_to_tensor

train_resize: &train_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 640
    padding_type: left_top
    padding_val: 0
    random_size: [15, 25]

test_resize: &test_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 640
    padding_type: left_top
    padding_val: 0

dataset:
  train:
    dataset:
      type: coco
      kwargs:
        meta_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/instances_train2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /mnt/lustre/share/DSK/datasets/mscoco2017/train2017
            color_mode: BGR
        transformer: [*mosaic, *random_perspective, *mixup, *augment_hsv, *flip, *train_resize, *to_tensor]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs:
            fix_seed: False
        batch_size: 8
  test:
    dataset:
      type: coco
      kwargs:
        meta_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/instances_val2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /mnt/lustre/share/DSK/datasets/mscoco2017/val2017
            color_mode: BGR
        transformer: [*test_resize, *to_tensor]
        evaluator:
          type: COCO
          kwargs:
            gt_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/instances_val2017.json
            iou_types: [bbox]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 8
  dataloader:
    type: base
    kwargs:
      num_workers: 8
      alignment: 32
      worker_init: True
      pad_type: batch_pad

trainer: # Required.
  max_epoch: &max_epoch 300             # total epochs for the training
  save_freq: 5
  test_freq: 5
  only_save_latest: True
  optimizer:                 # optimizer = SGD(params,lr=0.01,momentum=0.937,weight_decay=0.0005)
    register_type: yolov5
    type: SGD
    kwargs:
      lr: 0.00015625
      momentum: 0.9
      nesterov: True
      weight_decay: 0.0005      # weight_decay = 0.0005 * batch_szie / 64
  lr_scheduler:
    lr_register_type: yolox_base
    warmup_epochs: 5       # set to be 0 to disable warmup. When warmup,  target_lr = init_lr * total_batch_size
    warmup_type: yolox_cos
    type: YoloXCosineLR
    kwargs:
      T_max: *max_epoch
      min_lr_scale: 0.05
      no_aug_epoch: &no_aug_epoch 15

saver:
  save_dir: checkpoints/yolox_large_fp16
  results_dir: results_dir/yolox_large_fp16
  auto_resume: True

hooks:
  - type: yolox_noaug
    kwargs:
      no_aug_epoch: *no_aug_epoch
      max_epoch: *max_epoch
      transformer: [*augment_hsv, *flip, *train_resize, *to_tensor]
  - type: auto_save_best

ema:
  enable: True
  ema_type: exp
  kwargs:
    decay: 0.9998

net:
  - name: backbone
    type: yolox_l
    kwargs:
      out_layers: [2, 3, 4]
      out_strides: [8, 16, 32]
      normalize: {'type': 'solo_bn' }
      act_fn: {'type': 'Silu' }
  - name: neck
    prev: backbone
    type: YoloxPAFPN
    kwargs:
      depth: &depth 1.0
      out_strides: [8, 16, 32]
      act_fn: {'type': 'Silu'}
  - name: roi_head
    prev: neck
    type: YoloXHead
    kwargs:
      num_classes: *num_classes  # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
      width: 1.0
      num_point: &dense_points 1
      act_fn: {'type': 'Silu'}
  - name: yolox_post
    prev: roi_head
    type: yolox_post
    kwargs:
      num_classes: *num_classes  # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
      cfg:
        loc_loss:
          type: iou_loss
          kwargs:
            loss_type: square_iou
            loss_weight: 5.0
        cls_loss:
          type: sigmoid_cross_entropy
        obj_loss:
          type: sigmoid_cross_entropy
        anchor_generator:
          type: fcos # yolox
          kwargs:
            dense_points: *dense_points
            center: False
        roi_supervisor:
          type: ota
          kwargs:
            num_classes: *num_classes
            matcher:
              type: ota
              kwargs:
                num_classes: *num_classes
        roi_predictor:
          type: yolox
          kwargs:
            num_classes: *num_classes
            pre_nms_score_thresh: 0.01
            nms:
              type: naive
              nms_iou_thresh: 0.65
